name: upi_payment_qrcode_generator
description: UPI Payment QRCode Generator for User to scan and pay the Payee
  specific amount or user specific amount.
version: 1.6.0
homepage: https://github.com/AgnelSelvan/upi_payment_qrcode_generator

screenshots:
  - description: 'Examples of UPI Payment QRCode Generator'
    path: example/screenshots/output_1.png

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

topics:
  - upi
  - upi-qr-code
  - qr-code
  - india

funding:
  - https://github.com/sponsors/AgnelSelvan
